### ISSUE TITLE
Feature Request: Switch for the ventilation position

### ISSUE THREAD

**Issue by mapero** [mapero/esphome-hcpbridge#4]
Another question: Did you already thought about to integrate a switch for the ventilation position?

_Originally posted by @itapower in https://github.com/mapero/esphome-hcpbridge/issues/2#issuecomment-1887319841_

**Comment by mapero** [comment]
Hi @itapower

not yet. What would be the expectations?

It might be simpler to realize this with the service in esphome or home assistant. E.g. by using the https://esphome.io/components/button/index.html and triggering the vent service.

**Comment by itapower** [comment]
Hi mapero,
I have to apologize, I'm not an expert. 
I thought a switch could be easier to be used in automation (Home Assistant), like the light switch you already have in the esphome code.  
And yes, I managed the automations with triggering the vent position. 
So, it's not really necessary to have a switch for the vent position at the end. It's kind of nice to have.

**Comment by mapero** [comment]
Can you try the following (I have not tried yet):

Give your cover an id:
```yaml
cover:
  - platform: hcpbridge
    name: Garage Door
    id: garagedoor_cover ### <-- id of your cover
```

And add the following to your config:
```yaml
button:
  platform: template
  name: "Garage Door Vent"
  on_press:
    - lambda: |-
        auto ptr = id(garagedoor_cover);
        static_cast<esphome::hcpbridge::HCPBridgeCover*>(ptr)->on_go_to_vent();
```

It should create a button that calls the on_go_to_vent() method when pressed.

I will test it this weekend.
